const constants = {
  TEST: "TEST",
  OPEN_NEW_TICKET: "OPEN_NEW_TICKET",
  CLOSE_NEW_TICKET: "CLOSE_NEW_TICKET",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  FIRST_LOGIN_RESET: "FIRST_LOGIN_RESET",
  FIRST_LOGIN_REDIRECT: "FIRST_LOGIN_REDIRECT"
};

export default constants;
